[project]
name = "miller"
version = "0.1.0"
dependencies = [
    "numpy >= 1.25.0",
    "matplotlib >= 3.7.0",
    "tomli"
]

[project.optional-dependencies]
tests = ["pytest"]

[project.scripts]
miller = "miller:main"